# Generated by Django 3.0.3 on 2020-02-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('batch_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('phone_number', models.IntegerField(max_length=10)),
            ],
        ),
    ]
